name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3

      - name: ☕ Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: ⚙️ Usar Gradle 8.2
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.2

      - name: 🤖 Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: 🏗️ Build APK
        run: |
          gradle clean
          gradle build --refresh-dependencies
          gradle assembleDebug

      - name: 📦 Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
